#!/usr/bin/env bash
# copy a file into a server
if ! [[ $3 ]]
then
    echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
    exit 1
fi
path=$1
ip_ser=$2
user=$3
ssh_key=$4
scp -i $ssh_key -o StrictHostKeyChecking=no $path $user@$ip_ser:~/
