#!/usr/bin/env bash
# addinf the route to redirection
sudo apt-get -y update
sudo apt-get -y install nginx
sudo ufw allow 'Nginx HTTP'
sudo chmod 777 /var/www/html/index.nginx-debian.html
echo "Holberton School" > /var/www/html/index.nginx-debian.html
sudo service nginx restart
sudo chmod u+w /etc/nginx/sites-enabled/default
string="location /redirect_me {\n     rewrite ^/redirect_me(.*)$ https://www.youtube.com/watch?v=QH2-TGUlwu4/$1 permanent; \n}"
sudo sed -i "/# pass the PHP/i $string" /etc/nginx/sites-enabled/default
sudo service nginx restart
